name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
defaults:
  run:
    shell: bash
    
jobs:
  build:
    runs-on: ubuntu-latest
    container: espressif/idf:release-v4.3
    steps:      
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          . $IDF_PATH/export.sh
          idf.py build
