name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
defaults:
  run:
    shell: bash
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      # Runs a set of commands using the runners shell
      - name: ESP IDF Build
        uses: docker://espressif/idf:release-v4.3
        with:
          args: idf.py build
